version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "12:00"
      timezone: Europe/London
    target-branch: development
    open-pull-requests-limit: 10
