version: 2
updates:
  - package-ecosystem: composer
    directory: /website
    schedule:
      interval: monthly
      time: "12:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    target-branch: main

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: monthly
      time: "12:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    target-branch: main
