version: '3.7'
services:

  website:
    build: .
    image: orryverducci/website
    ports:
      - 8080:8080
    environment:
      TZ: Europe/London
    networks:
      - network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    environment:
      TZ: Europe/London
    networks:
      - network

networks:

  network:
    driver: bridge
