version: '3.7'
services:

  server:
    build:
      args:
        conf: staging.nginx.conf
    ports:
      - 8080:80

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
    environment:
      TZ: Europe/London
    networks:
      - app-network
